### ISSUE TITLE
Tim's desk needs to be tidy

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/for-review#1]
Can someone help me check I've tidied my desk?

Acceptance criteria:

- [ ] everything filed away or in neat piles
- [ ] can see the surface of the desk
- [ ] no food debris

**Comment by timcnicholls** [comment]
Anyone want to help with this? (Comment to check for Slack integration)

**Comment by dw96** [comment]
Serious question: Can I amend/comment on acceptance criteria if I think it doesn't cover all that the code actually is doing?

**Comment by SophieKSTFC** [comment]
I think this would be more of a review comment to say 'Your code meets all of the acceptance criteria you set out but I noticed it also does x,yz. Did you mean for this functionality to be in here or should it be factored out into a separate method?"

**Comment by dw96** [comment]
Good point.

**Comment by timcnicholls** [comment]
Does IBEX use issue templates?

**Comment by SophieKSTFC** [comment]
@timcnicholls they use them for PR's so when you open a PR it has a template that has the headings:

**Description of Work**

**Link to Ticket**

**Acceptance Criteria** 

**Tests**

**Code Review**

- [ ]  Is the code of an acceptable quality?
- [ ]  Do the changes function as described and is it robust?
- [ ]  Have the changes been documented in the release notes?

**Comment by timcnicholls** [comment]
That's useful thanks. Any suggestions for generic titles like this we could put in a template for our issues?

**Comment by EmmaHancock** [comment]
We could probably do something very similar but without the "Link to Ticket"? 
Is there a set code review template we could all base our reviews on as well? I've found a few online but they all vary slightly

**Comment by timcnicholls** [comment]
I think the "Link to Ticket" would prob be replaced by "Link to commits/PR/code" so it could be more generic?

**Comment by timcnicholls** [comment]
Closing this now as not needed.
