### ISSUE TITLE
LPD PSCU odin-lpdpower: Add support for leak detection hardware and python 3

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/for-review#3]
**Description of Work**

The PSCU control software in the odin-lpdpower package has been updated to:

1. Support the new leak detection hardware in lieu of one humidity channel
2. Support the latest release of odin-control, including python 3

**Link to Ticket**

[PR #50](https://github.com/stfc-aeg/odin-lpdpower/pull/50)

**Acceptance Criteria**

- [x] All code passes unit testing with >95% coverage
- [x] Leak detection hardware passes wet / dry physical testing

**Tests**

- [x] Tox unit tests / coverage
- [x] Physical demonstration with wet/dry leak detection cable

**Code Review**

- [x]  Is the code of an acceptable quality?
- [x]  Do the changes function as described and is it robust?
- [x]  Have the changes been documented (e.g. in commits, PR merges, release notes or documentation)?

**Comment by EmmaHancock** [comment]
Had a meeting with Tim to go through this code, and he explained how it all works and showed me the tests working. All the code is clean and I don't think any changes need to be made  😄

**Comment by timcnicholls** [comment]
👍 Thanks @EmmaHancock

**Comment by timcnicholls** [comment]
PR [#50](https://github.com/stfc-aeg/odin-lpdpower/pull/50) merged.
