### ISSUE TITLE
QEM-II backplane code

### ISSUE THREAD

**Issue by a-davi5** [stfc-aeg/for-review#4]
**Description of Work**
The work here encompassed the changes to refactor the backplane code so that the naming conventions used and in-code comments explained in more detail how the software interfaces to hardware.

**Link to commits/PR/code**
[PR#29](https://github.com/stfc-aeg/qemii-detector/pull/29)

**Acceptance Criteria**
The code should be easy to understand so that someone else with little knowledge of the system could understand and update it in future.

**Tests**

**Code Review**
 - [x] Is the code of an acceptable quality?
 - [x] Do the changes function as described and is it robust?
 - [x] Have the changes been documented (e.g. in commits, PR merges, release notes or documentation)?

**Comment by ANeaves** [comment]
Reviewed as part of changes made to the package structure of QEMII.
