### ISSUE TITLE
Qem-II Control Refactor

### ISSUE THREAD

**Issue by ANeaves** [stfc-aeg/for-review#5]
**Description of Work**
Refactored the odin_server code for Qemii so that the structure makes more sense.
This should go a ways to make the code more readable and maintanable, and also help in getting Travis to work.

**Link to commits/PR/code**
https://github.com/stfc-aeg/qemii-detector/pull/32
**Acceptance Criteria**
- [x] Is the code readable?
- [x] Does the structure of the two packages make sense
- [x] does it still function on Qemii? (might need demo)

**Tests**

**Code Review**
 - [x] Is the code of an acceptable quality?
 - [x] Do the changes function as described and is it robust?
 - [x] Have the changes been documented (e.g. in commits, PR merges, release notes or documentation)?

**Comment by dw96** [comment]
Looks good, @ANeaves demo'd code working fine. I've changed label to Complete.
