### ISSUE TITLE
Device Drivers Repo Creation

### ISSUE THREAD

**Issue by ANeaves** [stfc-aeg/for-review#6]
**Description of Work**
Separated out all the device drivers from different projects into their own repo, to make them more maintainable.

This is a brand new repo so the pull request doesn't have any previous diffs to compare to.

**Link to commits/PR/code**
https://github.com/stfc-aeg/odin-devices/pull/1

**Acceptance Criteria**
Please be aware I did not write the drivers myself, only copied them into the repo. I, alas, do not currently have the time to go through each one to make sure it follows current standards.
- [ ] Have all the drivers been copied correctly?
- [ ] Have all the tests been copied correctly?
- [ ] Does it build into a package that makes sense and is usable by other projects? (may need demo)

**Tests**
Run pytest -vv for full test report

**Code Review**
 - [ ] Is the code of an acceptable quality?
 - [ ] Do the changes function as described and is it robust?
 - [ ] Have the changes been documented (e.g. in commits, PR merges, release notes or documentation)?

**Comment by a-davi5** [comment]
I have downloaded and run the pytest test, Adam N explained the reason for why si570 test_fake has been skipped at this time . Folder structure looks sensible, all the drivers look to be there that are required for the QEM backplane, I have not checked the LPD ones.  Adam has demonstrated that it can be imported within python backplane code so I am happy.
